### ISSUE TITLE
Upcoming changes in the UdpDriverNode API

### ISSUE THREAD

**Issue by esteve** [andreaslebherz/ouster_ros2#1]
Hi! I'm one of the maintainers of the `udp_driver`, together with @JWhitleyWork. We're about to make some changes in the `UdpDriverNode` API, specifically removing support for `LifecycleNode` (which was never fully fleshed out) and converting the driver to be used as a ROS 2 component (https://docs.ros2.org/latest/api/rclcpp_components/ https://index.ros.org/doc/ros2/Tutorials/Composition/#using-components https://github.com/ros2/rclcpp/tree/master/rclcpp_components)

These changes can be found in https://github.com/esteve/transport_drivers/tree/remove-lifecycle, which right now only removes the `LifecycleNode` references, I'm about to make the component changes.

@andreaslebherz if you have a moment, could you test `ouster_ros2` against these changes to ensure a smooth transition? Thanks!

**Comment by andreaslebherz** [comment]
Hi Esteve, Thanks for informing me. I currently have no access to an Ouster sensor but I definitely will have a look at the changes and see how they influence my project. I will get in touch with you again once I read through the changes. Thanks!

**Comment by esteve** [comment]
@andreaslebherz thanks! For now we are removing `LifecycleNode`, which shouldn't affect you much. I've tested the changes with our Velodyne and Xsens drivers and they are fine. The more invasive changes will come later when we migrate to components.

**Comment by JWhitleyWork** [comment]
@andreaslebherz Any thoughts? We'd be happy to submit a PR applying the necessary changes to this repo if you'd like.

**Comment by andreaslebherz** [comment]
Hi @JWhitleyWork, @esteve  - sorry for dragging this out so long. I don't think that removing the `LifecycleNode` will effect me a lot since I hardly use the features provided by them. If you would provide a PR that would be absolute fine with me. Adjusting to the changed by myself would take me some time I guess.

**Comment by esteve** [comment]
@andreaslebherz in fact, you wouldn't have to make any changes, it's all in `udp_driver`. I had a brief look at the code in this repo and it doesn't seem to use any of the lifecyle stuff, so everything should be fine.

**Comment by JWhitleyWork** [comment]
The changes have been pushed to master on ros-drivers/transport_drivers. Feel free to close this issue.
